apiVersion: v1
kind: Secret
metadata: 
  name: backend-secrets
  namespace: muchtodo-ns
type: Opaque
stringData:
  MONGO_URI:  mongodb://admin:password@mongodb:27017/muchtodo?authSource=admin
  MONGO_URL: mongodb://admin:password@mongodb:27017/muchtodo?authSource=admin
  MONGODB_URI: mongodb://admin:password@mongodb:27017/muchtodo?authSource=admin 
